version: '3.9'

services:
  servicea:
    image: async-principle-servicea:v2.0.0
    build:
      context: ../../ServiceA/src/ServiceA
      dockerfile: Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - TZ=Asia/Bangkok
    depends_on:
      - serviceb

  serviceb:
    image: async-principle-serviceb:v2.0.0
    build:
      context: ../../ServiceB/src/ServiceB
      dockerfile: Dockerfile
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - TZ=Asia/Bangkok

volumes: {}
